apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

