apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskwebapp
spec:
  selector:
    matchLabels:
      app: flaskwebapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskwebapp
    spec:
      containers:
      - image: sriramsurendhran/ecommerce-webapp
        imagePullPolicy: Always
        name: flaskwebapp
        env:
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_APP
        - name: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_HOST
        - name: MYSQL_ROOT_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_PORT
        - name: MYSQL_ROOT_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_DB
